### ISSUE TITLE
[WIP]: Versão TypeScript

### ISSUE THREAD

**Issue by jonasmarco** [victorjean9/react-telefone-brasileiro#1]
Criei um Gist com uma versão em TypeScript caso alguém precise.
Também aceito sugestão de melhoria do script.

Segue o link

https://gist.github.com/jonasmarco/f7b571aa5b435df906ac982f71d31b8c

**Comment by devguilhermy** [comment]
Obrigado pelo código!

Só tive que fazer algumas alterações:
* `TYPES[getMask(value)]` passa a ser `TYPES[getMask(value) as keyof typeof TYPES]`, pois string não pode ser usado pra indexar o TYPES, na linha 56
* `TYPES[mask]` passa a ser `TYPES[mask as keyof typeof TYPES]`, pelo mesmo motivo, na linha 67

E ainda tive alguns problemas:
* Não dá pra passar a propriedade className pro input
* DevTools avisa vários erros: 

> Function components cannot be given refs. Attempts to access this ref will fail
> React does not recognize the `temDDD` prop on a DOM element - Mesmo pra separaNovo e separaDDD

Seria interessante colaborar com o @victorjean9 pra lançarmos uma versão tipada com essas correções
